export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_ALBUMS: "SET_ALBUMS",
  ADD_ALBUMS: "ADD_ALBUMS",
  SET_ARTISTS: "SET_ARTISTS",
  SET_FOLLOW_ARTISTS:"SET_FOLLOW_ARTISTS",
};
